/**********************************************\
*
*  Binary to C array converter
*  Andrey A. Ugolnik
*  andrey@ugolnik.info
*  Feb 17, 2023
*
*  Based on BIN2HPP.CPP
*  by Shabarshin A. A. 02.09.2000, 10.03.2003
*
\**********************************************/

#include <cstdio>
#include <cstdlib>
#include <cstring>

int main(int argc, char* argv[])
{
    if (argc < 2)
    {
        printf("Binary to C array converter.\n");
        printf("Andrey A. Ugolnik.\n");
        printf("Feb 17, 2023.\n");
        printf("Based on BIN2HPP.CPP by Shabarshin A. A.\n");
        printf("\n");
        printf("%s binary_file [options]\n", argv[0]);
        printf("     Options:\n");
        printf("      -s SIZE   - first SIZE bytes, whole binary_file by default.\n");
        printf("      -w WIDTH  - bytes per line, default 8.\n");
        printf("      -static   - adds static modificator.\n");
        printf("\n");
        return 1;
    }

    auto in = fopen(argv[1], "rb");
    if (in == nullptr)
    {
        return 1;
    }

    auto add_static = "";
    size_t size = 0;
    size_t width = 8;
    for (int i = 2; i < argc; i++)
    {
        if (!strncmp(argv[i], "-w", 2))
        {
            width = (size_t)atoi(argv[++i]);
        }
        else if (!strncmp(argv[i], "-s", 2))
        {
            size = strtoul(argv[++i], nullptr, 10);
        }
        else if (!strncmp(argv[i], "-static", 7))
        {
            add_static = "static ";
        }
    }

    if (size == 0)
    {
        fseek(in, 0L, SEEK_END);
        size = (size_t)ftell(in);
        fseek(in, 0L, SEEK_SET);
    }

    char str[100];
    strcpy(str, argv[1]);

    char str2[100];
    strcpy(str2, argv[1]);

    char* po = strrchr(str2, '.');
    if (po != nullptr)
    {
        *po = 0;
    }
    strcat(str2, ".h");

    auto out = fopen(str2, "wt");
    if (out == nullptr)
    {
        return 1;
    }

    for (size_t i = 0, length = strlen(str); i < length; i++)
    {
        if (str[i] >= 'A' && str[i] <= 'Z')
        {
            str[i] += 32;
        }
        if (!(str[i] >= 'a' && str[i] <= 'z') && !(str[i] >= '0' && str[i] <= '9'))
        {
            str[i] = '_';
        }
    }

    fprintf(out, "// Generated by bin2hpp\n");
    fprintf(out, "// https://bitbucket.org/andreyu/bin2hpp\n\n");
    fprintf(out, "%sconst size_t %s_size = %lu;\n", add_static, str, size);
    fprintf(out, "%sconst unsigned char %s[%lu] =\n{\n    ", add_static, str, size);
    for (size_t i = 0; i < size; i++)
    {
        fprintf(out, "0x%2.2X", fgetc(in));
        if (i != size - 1)
        {
            fputc(',', out);
        }
        if (i % width == width - 1)
        {
            fprintf(out, "\n    ");
        }
    }
    fprintf(out, "\n};\n");
    fclose(in);
    fclose(out);

    return 0;
}
